// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDiRgwy_O4Qh2A_zuYzdElCsPDB6rMd5s',
    appId: '1:28386661227:web:e67611012524eb3fa2322e',
    messagingSenderId: '28386661227',
    projectId: 'devathon-app',
    authDomain: 'devathon-app.firebaseapp.com',
    storageBucket: 'devathon-app.appspot.com',
    measurementId: 'G-TCRSZH3SDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9z8pIu5Cqse4bjmb8jvjUj-OJZucLqNo',
    appId: '1:28386661227:android:f81d8c3ff08fc0b4a2322e',
    messagingSenderId: '28386661227',
    projectId: 'devathon-app',
    storageBucket: 'devathon-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOvmftdNzL3XjYl4zVee9sIArY4NtEqvk',
    appId: '1:28386661227:ios:37ef195709ab17a2a2322e',
    messagingSenderId: '28386661227',
    projectId: 'devathon-app',
    storageBucket: 'devathon-app.appspot.com',
    iosBundleId: 'com.example.devathonApp',
  );
}
